### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by verbumfeit** [KaOS-Community-Packages/hddtemp#1]
I fixed the PKGBUILD but I can't compile it, probably because the compiler it was written for is pretty old (gnucc 6?) or is just me?

**Comment by demmm** [comment]
6 year old version.....of course no longer works.  Update to current version. Many add to KCP to never look back at what they added, so it is left to rot here, unless someone else finds an app useful and does the needed work for it.

**Comment by verbumfeit** [comment]
Yes, I'm currently going through each package and update them where possible. This is the most current version I found out there, so we can definitely remove this package. Can I do this as a member of the KaOS-Community-Packages group?

And of course _thank you_ for the awesome distro and your hard work!

**Comment by bvaudour** [comment]
It will be removed.
